const mongoose = require('mongoose');

const GameRoomSchema = new mongoose.Schema({
  roomId: {
    type: String,
    required: true,
    unique: true,
    trim: true,
  },
  players: [{
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    name: {
      type: String,
      required: true,
    },
    score: {
      type: Number,
      default: 0,
    },
  }],
  status: {
    type: String,
    enum: ['waiting', 'playing', 'finished'],
    default: 'waiting',
  },
  sequence: {
    type: String, // The current 6-digit number sequence generated by the math engine
    default: '',
  },
  round: {
    type: Number,
    default: 1,
  },
  maxRounds: {
    type: Number,
    default: 5, // Best out of 5 rounds
  },
}, {
  timestamps: true,
});

module.exports = mongoose.model('GameRoom', GameRoomSchema);